name: Release Suite

on:
  push:
    tags:
      - v0.*
      - v1.*
    branches:
      - arm64-pagesize-rebuild

jobs:
  Release:
    uses: ./.github/workflows/publish.yml
    with:
      git_ref: ${{ github.ref }}
      mode: Release
    secrets: inherit
